name: lf-api-client-core-dotnet-CI

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION_PREFIX: "2.0.1"

jobs:
  publish-preview:
    runs-on: windows-latest
    environment: preview
    env:
      PACKAGE_VERSION: "${{ env.VERSION_PREFIX }}-beta-${{ github.run_id }}"
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration release
    - name: Packaging
      run: dotnet pack --no-build --configuration release /p:version=${{ env.PACKAGE_VERSION }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: package-preview-artifact
        path: ${{ github.workspace }}/src/bin/Release/*.nupkg

    #- name: Publish to Nuget.org
    #  run: dotnet nuget push ./src/bin/Release/*.nupkg --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
    - name: Tag commit
      uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ env.PACKAGE_VERSION }}
        commit_sha: ${{ github.sha }}
        message: Workflow run ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
